import { EmailValidator, Validators } from '@angular/forms';
import {
    FormTemplateModel,
    Orientations,
    TypeFields,
} from 'app/components/dinamic-form/models/form-model';
import { NoDecimalValidator } from 'app/components/dinamic-form/validators/noDecimalValidator';
import { TwoDecimalValidator } from 'app/components/dinamic-form/validators/twoDecimalValidator';
import { NoWhitespaceValidator } from 'app/components/dinamic-form/validators/noWhiteSpacesValidator';
import { DataService } from '../data/data.service';

export const Forms: FormList = {
    LoginForm: {
        Code: 'LoginForm',
        Orientation: Orientations.Vertical,
        BtnText: 'SIGN_IN.FORM.SUBMIT',
        BtnFull: true,
        CancelButton: false,
        Fields: [
            {
                Code: 'userName',
                FieldType: { Name: TypeFields.Text },
                Id: 1,
                Index: 1,
                IsEditable: true,
                IsRequired: true,
                Name: 'User',
                Title: 'SIGN_IN.FORM.USER',
                Value: undefined,
                Rules: [Validators.required, Validators.email],
            },
            {
                Code: 'password',
                FieldType: { Name: TypeFields.Password },
                Id: 2,
                Index: 2,
                IsEditable: true,
                IsRequired: true,
                Name: 'Password',
                Title: 'SIGN_IN.FORM.PASSWORD',
                Icon: 'heroicons_solid:eye',
                IconAfter: 'heroicons_solid:eye-slash',
                Value: undefined,
                Rules: [Validators.required],
            },
        ],
    },
    ForgotPasswordForm: {
        Code: 'ForgotPasswordForm',
        Orientation: Orientations.Vertical,
        BtnText: 'FORGOT_PASSWORD.FORM.SUBMIT',
        CancelButton: false,
        BtnFull: true,
        Fields: [
            {
                Code: 'email',
                FieldType: { Name: TypeFields.Text },
                Id: 1,
                Index: 1,
                IsEditable: true,
                IsRequired: true,
                Name: 'Email',
                Title: 'FORGOT_PASSWORD.FORM.EMAIL',
                Value: undefined,
                Rules: [Validators.email, Validators.required],
            },
        ],
    },
    SignUpForm: {
        Code: 'SignUpForm',
        Orientation: Orientations.Vertical,
        BtnText: 'SIGN_UP.FORM.SUBMIT',
        CancelButton: false,
        BtnFull: true,
        Fields: [
            {
                Code: 'name',
                FieldType: { Name: TypeFields.Text },
                Id: 1,
                Index: 1,
                IsEditable: true,
                IsRequired: true,
                Name: 'Name',
                Title: 'SIGN_UP.FORM.NAME',
                Value: undefined,
                Rules: [Validators.required],
            },
            {
                Code: 'lastName',
                FieldType: { Name: TypeFields.Text },
                Id: 2,
                Index: 2,
                IsEditable: true,
                IsRequired: true,
                Name: 'LastName',
                Title: 'SIGN_UP.FORM.LASTNAME',
                Value: undefined,
                Rules: [Validators.required],
            },
            {
                Code: 'password',
                FieldType: { Name: TypeFields.Password },
                Id: 3,
                Index: 3,
                IsEditable: true,
                IsRequired: true,
                Name: 'Password',
                Title: 'SIGN_UP.FORM.PASSWORD',
                Icon: 'heroicons_solid:eye',
                IconAfter: 'heroicons_solid:eye-slash',
                Value: undefined,
                Rules: [ Validators.required, Validators.minLength(8), Validators.pattern(/^(?=(.*\d){2})(?=.*[A-Z])[0-9a-zA-Z!@#$%^&*()_\-+|~=\\`{}[\]:"";'<>?,./)(]{8,32}$/)],
            },
            {
                Code: 'establishment',
                FieldType: { Name: TypeFields.Text },
                Id: 4,
                Index: 4,
                IsEditable: true,
                IsRequired: true,
                Name: 'Establishment',
                Title: 'SIGN_UP.FORM.ESTABLISHMENT',
                Value: undefined,
                Rules: [Validators.required],
            },
            {
                Code: 'email',
                FieldType: { Name: TypeFields.Text },
                Id: 3,
                Index: 3,
                IsEditable: true,
                IsRequired: true,
                Name: 'Email',
                Title: 'SIGN_UP.FORM.EMAIL',
                Value: undefined,
                Rules: [Validators.email, Validators.required],
            },

            {
                Code: 'phoneNumber',
                FieldType: { Name: TypeFields.PhoneNumber },
                Id: 4,
                Index: 4,
                IsEditable: true,
                IsRequired: true,
                Name: 'PhoneNumber',
                Title: 'SIGN_UP.FORM.PHONE',
                Value: undefined,
                Rules: [
                    Validators.required,
                    Validators.minLength(8),
                    NoWhitespaceValidator(),
                ],
            },
        ],
    },
    InformationForm: {
        Code: 'InformationForm',
        Orientation: Orientations.Columns,
        BtnText: 'ESTABLISHMENTS.FORM.SUBMIT',
        CancelButton: false,
        BtnFull: false,
        Columns: '2',
        Fields: [
            {
                Code: 'id',
                FieldType: { Name: TypeFields.Text },
                Id: 1,
                Index: 1,
                IsEditable: false,
                IsRequired: true,
                Icon: "check",
                Name: 'id',
                Title: 'ESTABLISHMENTS.FORM.ID',
                Value: undefined,
                Rules: [Validators.required],
            },
            {
                Code: 'name',
                FieldType: { Name: TypeFields.Text },
                Id: 2,
                Index: 2,
                IsEditable: false,
                IsRequired: true,
                Name: 'name',
                Title: 'ESTABLISHMENTS.FORM.NAME',
                Value: undefined,
                Rules: [Validators.required],
            },
            {
                Code: 'address',
                FieldType: { Name: TypeFields.Text },
                Id: 3,
                Index: 3,
                IsEditable: true,
                IsRequired: true,
                Name: 'address',
                Title: 'ESTABLISHMENTS.FORM.ADDRESS',
                Value: undefined,
                Rules: [Validators.required],
            },
            {
                Code: 'city',
                FieldType: { Name: TypeFields.Text },
                Id: 4,
                Index: 4,
                IsEditable: true,
                IsRequired: true,
                Name: 'city',
                Title: 'ESTABLISHMENTS.FORM.CITY',
                Value: undefined,
                Rules: [Validators.required],
            },
            {
                Code: 'state',
                FieldType: { Name: TypeFields.Text },
                Id: 5,
                Index: 5,
                IsEditable: true,
                IsRequired: true,
                Name: 'state',
                Title: 'ESTABLISHMENTS.FORM.STATE',
                Value: undefined,
                Rules: [Validators.required],
            },
            {
                Code: 'postalCode',
                FieldType: { Name: TypeFields.Text },
                Id: 6,
                Index: 6,
                IsEditable: true,
                IsRequired: true,
                Name: 'postalCode',
                Title: 'ESTABLISHMENTS.FORM.POSTAL_CODE',
                Value: undefined,
                Rules: [Validators.required],
            },
            {
                Code: 'enabled',
                FieldType: { Name: TypeFields.Checkbox },
                Id: 7,
                Index: 7,
                IsEditable: false,
                IsRequired: true,
                Name: 'enabled',
                Title: 'ESTABLISHMENTS.FORM.STATUS',
                Options: [],
                Value: undefined,
                Rules: [Validators.required],
            },
        ],
    },
    ProfileForm: {
        Code: 'ProfileForm',
        Orientation: Orientations.Vertical,
        BtnText: 'PROFILE_FORM.FORM.SUBMIT',
        BtnFull: false,
        CancelButton: false,
        Fields: [
            {
                Code: 'firstName',
                FieldType: { Name: TypeFields.Text },
                Id: 1,
                Index: 1,
                IsEditable: true,
                IsRequired: true,
                Name: 'firstName',
                Title: 'PROFILE_FORM.FORM.NAME',
                Value: undefined,
                Rules: [Validators.required],
            },
            {
                Code: 'lastName',
                FieldType: { Name: TypeFields.Text },
                Id: 2,
                Index: 2,
                IsEditable: true,
                IsRequired: true,
                Name: 'lastName',
                Title: 'PROFILE_FORM.FORM.LASTNAME',
                Value: undefined,
                Rules: [Validators.required],
            },
            {
                Code: 'id',
                FieldType: { Name: TypeFields.Text },
                Id: 3,
                Index: 3,
                IsEditable: false,
                IsRequired: true,
                Name: 'id',
                Title: 'userId',
                Hidden: true,
                Value: undefined,
                Rules: [Validators.required],
            },
            {
                Code: 'timeZone',
                FieldType: { Name: TypeFields.Select },
                Id: 4,
                Index: 4,
                IsEditable: true,
                IsRequired: true,
                Name: 'timeZone',
                Title: 'USERS.FORM.TIMEZONE',
                Value: undefined,
                Options: [],
                Rules: [Validators.required],
            },
            {
                Code: 'language',
                FieldType: { Name: TypeFields.Select },
                Id: 5,
                Index: 5,
                IsEditable: true,
                IsRequired: true,
                Name: 'language',
                Title: 'USERS.FORM.LANGUAGE',
                Value: undefined,
                Options: [],
                Rules: [Validators.required],
            }

        ],
    },
    UpdatePasswordForm: {
        Code: 'UpdatePasswordForm',
        Orientation: Orientations.Vertical,
        BtnText: 'RESET_PASSWORD_FORM.FORM.SUBMIT',
        BtnFull: false,
        CancelButton: false,
        Fields: [
            {
                Code: 'newPassword',
                FieldType: { Name: TypeFields.Password },
                Id: 1,
                Index: 1,
                IsEditable: true,
                IsRequired: true,
                Name: 'newPassword',
                Title: 'RESET_PASSWORD_FORM.FORM.NEW_PASSWORD',
                Icon: 'heroicons_solid:eye',
                IconAfter: 'heroicons_solid:eye-slash',
                Value: undefined,
                Rules: [Validators.required,Validators.minLength(8), Validators.pattern(/^(?=(.*\d){2})(?=.*[A-Z])[0-9a-zA-Z!@#$%^&*()_\-+|~=\\`{}[\]:"";'<>?,./)(]{8,32}$/)],
            },
            {
                Code: 'newPasswordConfirm',
                FieldType: { Name: TypeFields.Password },
                Id: 2,
                Index: 2,
                IsEditable: true,
                IsRequired: true,
                Name: 'newPasswordConfirm',
                Title: 'RESET_PASSWORD_FORM.FORM.NEW_PASSWORD_CONFIRM',
                Icon: 'heroicons_solid:eye',
                IconAfter: 'heroicons_solid:eye-slash',
                Value: undefined,
                Rules: [Validators.required,Validators.minLength(8), Validators.pattern(/^(?=(.*\d){2})(?=.*[A-Z])[0-9a-zA-Z!@#$%^&*()_\-+|~=\\`{}[\]:"";'<>?,./)(]{8,32}$/)],
            }
        ],
    },
    ResetPasswordForm: {
        Code: 'ResetPasswordForm',
        Orientation: Orientations.Vertical,
        BtnText: 'RESET_PASSWORD_FORM.FORM.SUBMIT',
        BtnFull: true,
        CancelButton: false,
        Fields: [
            {
                Code: 'newPassword',
                FieldType: { Name: TypeFields.Password },
                Id: 1,
                Index: 1,
                IsEditable: true,
                IsRequired: true,
                Name: 'newPassword',
                Title: 'RESET_PASSWORD_FORM.FORM.NEW_PASSWORD',
                Icon: 'heroicons_solid:eye',
                IconAfter: 'heroicons_solid:eye-slash',
                Value: undefined,
                Rules: [Validators.required,Validators.minLength(8), Validators.pattern(/^(?=(.*\d){2})(?=.*[A-Z])[0-9a-zA-Z!@#$%^&*()_\-+|~=\\`{}[\]:"";'<>?,./)(]{8,32}$/)],
            },
            {
                Code: 'newPasswordConfirm',
                FieldType: { Name: TypeFields.Password },
                Id: 2,
                Index: 2,
                IsEditable: true,
                IsRequired: true,
                Name: 'newPasswordConfirm',
                Title: 'RESET_PASSWORD_FORM.FORM.NEW_PASSWORD_CONFIRM',
                Icon: 'heroicons_solid:eye',
                IconAfter: 'heroicons_solid:eye-slash',
                Value: undefined,
                Rules: [Validators.required,Validators.minLength(8), Validators.pattern(/^(?=(.*\d){2})(?=.*[A-Z])[0-9a-zA-Z!@#$%^&*()_\-+|~=\\`{}[\]:"";'<>?,./)(]{8,32}$/)],
            }
        ],
    },
    RoleForm: {
        Code: 'RoleForm',
        Orientation: Orientations.Vertical,
        BtnText: 'ROLES.FORM.SUBMIT',
        BtnFull: false,
        CancelButton: false,
        Fields: [
            {
                Code: 'name',
                FieldType: { Name: TypeFields.Text },
                Id: 1,
                Index: 1,
                IsEditable: true,
                IsRequired: true,
                Name: 'name',
                Title: 'ROLES.FORM.NAME',
                Value: undefined,
                Rules: [Validators.required],
            },
            {
                Code: 'id',
                FieldType: { Name: TypeFields.Text },
                Id: 2,
                Index: 2,
                IsEditable: false,
                IsRequired: true,
                Name: 'id',
                Title: 'id',
                Hidden: true,
                Value: undefined,
                Rules: [Validators.required],
            }
        ],
    },
    NewUserForm: {
        Code: 'NewUserForm',
        Orientation: Orientations.Columns,
        BtnText: 'USERS.FORM.SUBMIT',
        BtnFull: false,
        CancelButton: true,
        BtnCancelText: 'USERS.FORM.CANCEL',
        Columns:'2',
        Fields: [
            {
                Code: 'name',
                FieldType: { Name: TypeFields.Text },
                Id: 1,
                Index: 1,
                IsEditable: true,
                IsRequired: true,
                Name: 'name',
                Title: 'USERS.FORM.NAME',
                Value: undefined,
                Rules: [Validators.required],
            },
            {
                Code: 'lastName',
                FieldType: { Name: TypeFields.Text },
                Id: 2,
                Index: 2,
                IsEditable: true,
                IsRequired: true,
                Name: 'lastName',
                Title: 'USERS.FORM.LASTNAME',
                Value: undefined,
                Rules: [Validators.required]
            },
            {
                Code: 'email',
                FieldType: { Name: TypeFields.Text },
                Id: 3,
                Index: 3,
                IsEditable: true,
                IsRequired: true,
                Name: 'email',
                Title: 'USERS.FORM.EMAIL',
                Value: undefined,
                Rules: [Validators.required, Validators.email],
            },
            {
                Code: 'role',
                FieldType: { Name: TypeFields.Select, Multiple: true },
                Id: 4,
                Index: 4,
                IsEditable: true,
                IsRequired: true,
                Name: 'role',
                Title: 'USERS.FORM.ROLE',
                Value: undefined,
                Options: [],
                Rules: [Validators.required],
            },
            {
                Code: 'timeZone',
                FieldType: { Name: TypeFields.Select },
                Id: 5,
                Index: 5,
                IsEditable: true,
                IsRequired: true,
                Name: 'timeZone',
                Title: 'USERS.FORM.TIMEZONE',
                Value: undefined,
                Options: [],
                Rules: [Validators.required],
            },
            {
                Code: 'language',
                FieldType: { Name: TypeFields.Select },
                Id: 6,
                Index: 6,
                IsEditable: true,
                IsRequired: true,
                Name: 'language',
                Title: 'USERS.FORM.LANGUAGE',
                Value: undefined,
                Options: [],
                Rules: [Validators.required],
            }

        ],
    },
    EditUserForm: {
        Code: 'EditUserForm',
        Orientation: Orientations.Columns,
        BtnText: 'USERS.FORM.SUBMIT',
        BtnFull: false,
        CancelButton: true,
        BtnCancelText: 'USERS.FORM.CANCEL',
        Columns:'2',
        Fields: [
            {
                Code: 'name',
                FieldType: { Name: TypeFields.Text },
                Id: 1,
                Index: 1,
                IsEditable: true,
                IsRequired: true,
                Name: 'name',
                Title: 'USERS.FORM.NAME',
                Value: undefined,
                Rules: [Validators.required],
            },
            {
                Code: 'lastName',
                FieldType: { Name: TypeFields.Text },
                Id: 2,
                Index: 2,
                IsEditable: true,
                IsRequired: true,
                Name: 'lastName',
                Title: 'USERS.FORM.LASTNAME',
                Value: undefined,
                Rules: [Validators.required],
            },
            {
                Code: 'email',
                FieldType: { Name: TypeFields.Text },
                Id: 3,
                Index: 3,
                IsEditable: false,
                IsRequired: true,
                Name: 'email',
                Title: 'USERS.FORM.EMAIL',
                Value: undefined,
                Rules: [Validators.required, Validators.email],
            },
            {
                Code: 'role',
                FieldType: { Name: TypeFields.Select, Multiple: true },
                Id: 4,
                Index: 4,
                IsEditable: true,
                IsRequired: true,
                Name: 'role',
                Title: 'USERS.FORM.ROLE',
                Value: undefined,
                Options: [],
                Rules: [Validators.required],
            },
            {
                Code: 'timeZone',
                FieldType: { Name: TypeFields.Select},
                Id: 5,
                Index: 5,
                IsEditable: true,
                IsRequired: true,
                Name: 'timeZone',
                Title: 'USERS.FORM.TIMEZONE',
                Value: undefined,
                Options: [],
                Rules: [Validators.required],
            },
            {
                Code: 'language',
                FieldType: { Name: TypeFields.Select},
                Id: 6,
                Index: 6,
                IsEditable: true,
                IsRequired: true,
                Name: 'language',
                Title: 'USERS.FORM.LANGUAGE',
                Value: undefined,
                Options: [],
                Rules: [Validators.required],
            }
        ],
    },
};

type FormList = {
    [key: string]: FormTemplateModel;
};
